routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix'=>'admin/','namespace'=>'Admin', 'as'=>'admin.'],function(){
    Route::group(['middleware'=>'admin'],function(){
        //  Admin & Writter main page
        Route::get('','AdminHomeController@index')->name('homepage');
        Route::post('mark-as-read','AdminHomeController@markOneAsRead')->name('adminMarkAsRead');
        Route::get('mark-all-as-read','AdminHomeController@markAllAsRead')->name('adminMarkAllAsRead');

        //  Categories | Only Admin
        Route::resource('categories','CategoriesController');

        //  User | Full control for Admin | Only profile for Writter
        Route::resource('users','UserController');

        //  Post | Full control for Admin | Only post from Writter
        Route::resource('post','PostController');

        //  Notification | Full control for Admin | Only view from Writter
        Route::resource('notification','NotificationController');

        //  Image | Full control for Admin | Only image from Writter
        Route::resource('image','ImageController');

        // Comment| Only Admin
        Route::resource('comment','AdminCommentController')->only('index','edit','destroy');
    });
});

// All authenticated user
Route::group(['middleware'=>'auth'],function(){
    // Comment
    Route::controller('User\UserCommentController')->group(function(){
        Route::post('/comment/{post}','store')->name('pComment');
        Route::delete('/comment/{comment}','destroy')->name('deleteComment');
    });
    // Notification
    Route::controller('UserNotificationController')->group(function(){
        Route::post('/mark-as-read','markOneAsRead')->name('markAsRead');
        Route::get('/mark-all-read','markAllAsRead')->name('markAllRead');
    });
    // Like and unlike post
    Route::controller('User\LikeController')->group(function(){
        Route::post('/like/{post}','like')->name('like');
        Route::post('/unlike/{post}','unlike')->name('unlike');
    });
    // Profile
    Route::controller('User\UserProfileController')->group(function(){
        Route::get('/profile','profile')->name('user.profile');
        Route::put('/profile/{user}','update')->name('user.update');

    });
});

// Lang
Route::get('lang/{lang}','LanguageController')->name("lang");

// Authentication
    // Socialite
Route::controller('AuthProviderController')->group(function(){
    Route::get('/auth/{provider}/redirect', 'redirect')->name('socialLogin');
    Route::get('/auth/{provider}/callback', 'callback');
});
    // Setup password
Route::controller('User\UserSetupPasswordController')->group(function(){
    Route::get('/setup-password','index')->name('setupPassword');
    Route::post('/setup-password/sent','update')->name('pSetupPassword');
});
    //Manual
Route::controller('AuthController')->group(function(){
    Route::get('login','Login')->name('login');
    Route::post('login','pLogin')->name('pLogin');
    Route::get('register','register')->name('register');
    Route::post('register','pRegister')->name('pRegister');
    Route::get('logout','Logout')->name('logout');
});

// Page navigation
Route::get('/','User\UserHomeController')->name('homepage');
Route::get('post/{post}','User\ShowPostController@show')->name('showPost');
Route::get('filter','User\UserFilterController@filter')->name('postFilter');
Route::get('category/{category}','User\PostCategoryController')->name('postCategory');
Route::get('tag/{tag}','User\PostTagController')->name('postTag');


// Only for testing purpose
Route::get('/test',function(){
    return view('test');
});

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\UserRole;
use App\Models\SendNotifications;
use App\Http\Controllers\Controller;
use App\Http\Requests\Notification\SendNotificationRequest;
use App\Http\Requests\Notification\UpdateNotificationRequest;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class NotificationController extends Controller
{
    
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $receivedNotifications = Auth::user()->notifications;
        $notifications=[];
        if(Gate::allows('only-admin',Auth::user())){
            $notifications = SendNotifications::all();
        }
        return view('admin.notification.index', compact('receivedNotifications','notifications'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $users = User::select('id','name')->get();
        return view('admin.notification.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(SendNotificationRequest $request)
    {
        $data = $request->validated();
        $data = array_merge($data,['status'=>'pending']);
        SendNotifications::create($data);
        return redirect()->route('admin.notification.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(SendNotifications $notification)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(SendNotifications $notification)
    {
        $users = User::select('id','name')->get();
        return view('admin.notification.edit',compact('notification','users'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateNotificationRequest $request, SendNotifications $notification)
    {
        $data = $request->validated();
        $notification->update($data);
        return redirect()->route('admin.notification.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(SendNotifications $notification)
    {
        $notification->forceDelete();
        return redirect()->route('admin.notification.index');
    }
}

resources/views/admin/notification/create.blade.php
@extends('admin.homepage')
@section('content')
<h3>{{__('news.plural.notification')}}</h3>
<hr>
<div>
    <form action="{{route('admin.notification.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">{{__('user.plural.title')}}</label>
            <input type="text" name="title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{__('user.plural.msg')}}</label>
            <input type="text" name="msg" class="form-control" id="exampleInputPassword1">
        </div>
        <label for="option">{{__('news.plural.choose-receiver')}}</label>
        <div class="d-flex pb-3" id="option">
            <select id="users" name="type" class="form-select">
                <option id="all" value="all" selected>{{__('user.plural.all')}}</option>
                <option id="writer" value="writer">{{__('user.plural.writer')}}</option>
                <option id="user" value="user">{{__('user.plural.only-user')}}</option>
                <option id="other" value="other">{{__('user.plural.other')}}</option>
            </select>
            <br>
            <select id="select-user" name="receiver_id[]" class="form-select w-50" disabled>
                @foreach ($users as $user)
                    <option value="{{$user->id}}">{{$user->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">{{__('user.plural.choose-send-date')}}</label>
            <input name="send_date" type="datetime-local" value="{{date('Y-m-d H:i')}}"/>
        </div>
        <button type="submit" class="btn btn-primary">{{__('user.user.send')}}</button>
    </form>
</div>
@endsection
@section('script')
<script>
$(document).ready(function(){
    $("#users").change(function(){
        if($("#other:selected").length>0){
            $('#select-user').removeAttr('disabled')
        }
        if($("#all:selected").length>0){
            $('#select-user').attr('disabled','disabled')
        }
        if($("#writer:selected").length>0){
            $('#select-user').attr('disabled','disabled')
        }
        if($("#user:selected").length>0){
            $('#select-user').attr('disabled','disabled')
        }
    })
})
$('#select-user').select2({
    multiple:true,
});
</script>
@endsection

resources/views/admin/notification/edit.blade.php
@extends('admin.homepage')
@section('content')
<h3>{{__('news.plural.notification')}}</h3>
<hr>
<div>
    <form action="{{route('admin.notification.update',$notification->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="exampleInputEmail1">{{__('user.plural.title')}}</label>
            <input type="text" name="title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{$notification->title}}">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">{{__('user.plural.msg')}}</label>
            <input type="text" name="msg" class="form-control" id="exampleInputPassword1" value="{{$notification->msg}}">
        </div>
        <label for="option">{{__('news.plural.choose-receiver')}}</label>
        <div class="d-flex pb-3" id="option">
            <select id="users" name="type" class="form-select">
                <option id="all" value="all" {{$notification->type=='all'?'selected':''}}>{{__('user.plural.all')}}</option>
                <option id="writer" value="writer" {{$notification->type=='writer'?'selected':''}}>{{__('user.plural.writer')}}</option>
                <option id="user" value="user" {{$notification->type=='user'?'selected':''}}>{{__('user.plural.only-user')}}</option>
                <option id="other" value="other" {{$notification->type=='other'?'selected':''}}>{{__('user.plural.other')}}</option>
            </select>
            <br>
            <select id="select-user" name="receiver_id[]" class="form-select w-50" disabled>
                @foreach ($users as $user)
                    <option value="{{$user->id}}">{{$user->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">{{__('user.plural.choose-send-date')}}</label>
            <input name="send_date" type="datetime-local" value="{{$notification->send_date}}"/>
        </div>
        <button type="submit" class="btn btn-primary">{{__('user.user.send')}}</button>
    </form>
</div>
@endsection
@section('script')
<script>
$(document).ready(function(){
    $("#users").change(function(){
        if($("#other:selected").length>0){
            $('#select-user').removeAttr('disabled')
        }
        if($("#all:selected").length>0){
            $('#select-user').attr('disabled','disabled')
        }
        if($("#writer:selected").length>0){
            $('#select-user').attr('disabled','disabled')
        }
        if($("#user:selected").length>0){
            $('#select-user').attr('disabled','disabled')
        }
    })
})
$('#select-user').select2({
    multiple:true,
});
</script>
@endsection

resources/views/admin/notification/index.blade.php
@extends('admin.homepage')
@section('content')
<h4>{{__('news.plural.received')}}</h4>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">{{__('user.plural.content')}}</th>
      <th scope="col">{{__('user.plural.readed')}}</th>
      <th scope="col">{{__('user.plural.created')}}</th>
    </tr>
  </thead>
  <tbody>
      @foreach ($receivedNotifications as $key=>$notification)
        <tr>
          <td>{{$key+1}}</td>
          <td>{{$notification['data']['msg']}}</td>
          <td>{{$notification['read_at']}}</td>
          <td>{{$notification['created_at']}}</td>
        </tr>
      @endforeach
  </tbody>
</table>
@can('only-admin',Auth::user())
<hr></hr>
<h4>{{__('news.plural.sent')}}</h4>
<a href="{{route('admin.notification.create')}}">
  <button type="button" class="btn btn-primary">{{__('news.plural.send-btn')}}</button>
</a>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">{{__('news.plural.type')}}</th>
      <th scope="col">{{__('news.plural.receiver')}}</th>
      <th scope="col">{{__('news.plural.title')}}</th>
      <th scope="col">{{__('news.plural.content')}}</th>
      <th scope="col">{{__('news.plural.created')}}</th>
      <th scope="col">{{__('news.plural.send-date')}}</th>
      <th scope="col">{{__('news.plural.status')}}</th>
      <th scope="col">{{__('news.plural.action')}}</th>
    </tr>
  </thead>
  <tbody>
      @foreach ($notifications as $key=>$notification)
        <tr>
          <td>{{$key+1}}</td>
          <td>{{$notification->type}}</td>
          <td>{{$notification->receiver_id!==null&&$notification->type=='other'?count($notification->receiver_id):$notification->type}}</td>
          <td>{{$notification->title}}</td>
          <td>{{$notification->msg}}</td>
          <td>{{$notification->created_at}}</td>
          <td>{{$notification->send_date}}</td>
          <td>{{$notification->status}}</td>
          <td class="d-flex">
            @if ($notification->status=='pending')
              <a href="{{route('admin.notification.edit',$notification->id)}}">
                <button type="button" class="btn btn-warning">{{__('news.user.edit')}}</button>
              </a>
            @endif
            <form method="post" action="{{route('admin.notification.destroy',$notification->id)}}">
              @method('delete')
              @csrf
              <button type="submit" class="deleteBtn btn btn-danger">{{__('news.user.delete')}}</button>
            </form>
          </td>
        </tr>
      @endforeach
  </tbody>
</table>
@endcan
<script>
$('.deleteBtn').click(function(e){
    e.preventDefault()
    if (confirm('{{__('news.plural.confirm')}}')) {
        $(e.target).closest('form').submit()
    }
})
</script>
@endsection