routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix'=>'admin/','namespace'=>'Admin', 'as'=>'admin.'],function(){
    Route::group(['middleware'=>'admin'],function(){
        //  Admin & Writter main page
        Route::get('','AdminHomeController@index')->name('homepage');
        Route::post('mark-as-read','AdminHomeController@markOneAsRead')->name('adminMarkAsRead');
        Route::get('mark-all-as-read','AdminHomeController@markAllAsRead')->name('adminMarkAllAsRead');

        //  Categories | Only Admin
        Route::resource('categories','CategoriesController');

        //  User | Full control for Admin | Only profile for Writter
        Route::resource('users','UserController');

        //  Post | Full control for Admin | Only post from Writter
        Route::resource('post','PostController');

        //  Notification | Full control for Admin | Only view from Writter
        Route::resource('notification','NotificationController');

        //  Image | Full control for Admin | Only image from Writter
        Route::resource('image','ImageController');

        // Comment| Only Admin
        Route::resource('comment','AdminCommentController')->only('index','edit','destroy');
    });
});

// All authenticated user
Route::group(['middleware'=>'auth'],function(){
    // Comment
    Route::controller('User\UserCommentController')->group(function(){
        Route::post('/comment/{post}','store')->name('pComment');
        Route::delete('/comment/{comment}','destroy')->name('deleteComment');
    });
    // Notification
    Route::controller('UserNotificationController')->group(function(){
        Route::post('/mark-as-read','markOneAsRead')->name('markAsRead');
        Route::get('/mark-all-read','markAllAsRead')->name('markAllRead');
    });
    // Like and unlike post
    Route::controller('User\LikeController')->group(function(){
        Route::post('/like/{post}','like')->name('like');
        Route::post('/unlike/{post}','unlike')->name('unlike');
    });
    // Profile
    Route::controller('User\UserProfileController')->group(function(){
        Route::get('/profile','profile')->name('user.profile');
        Route::put('/profile/{user}','update')->name('user.update');

    });
});

// Lang
Route::get('lang/{lang}','LanguageController')->name("lang");

// Authentication
    // Socialite
Route::controller('AuthProviderController')->group(function(){
    Route::get('/auth/{provider}/redirect', 'redirect')->name('socialLogin');
    Route::get('/auth/{provider}/callback', 'callback');
});
    // Setup password
Route::controller('User\UserSetupPasswordController')->group(function(){
    Route::get('/setup-password','index')->name('setupPassword');
    Route::post('/setup-password/sent','update')->name('pSetupPassword');
});
    //Manual
Route::controller('AuthController')->group(function(){
    Route::get('login','Login')->name('login');
    Route::post('login','pLogin')->name('pLogin');
    Route::get('register','register')->name('register');
    Route::post('register','pRegister')->name('pRegister');
    Route::get('logout','Logout')->name('logout');
});

// Page navigation
Route::get('/','User\UserHomeController')->name('homepage');
Route::get('post/{post}','User\ShowPostController@show')->name('showPost');
Route::get('filter','User\UserFilterController@filter')->name('postFilter');
Route::get('category/{category}','User\PostCategoryController')->name('postCategory');
Route::get('tag/{tag}','User\PostTagController')->name('postTag');


// Only for testing purpose
Route::get('/test',function(){
    return view('test');
});

app/Models/Comment.php
<?php

namespace App\Models;

use App\Enums\Status;
use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Comment extends Model
{
    use HasFactory, SoftDeletes, Filterable;

    protected $table = 'comment';

    protected $fillable = [
        'user_id',
        'post_id',
        'content',
        'status',
    ];

    protected $cast = [
        'status' => Status::class,
    ];

    public function isPending(){
        return $this->status===Status::Pending;
    }
    
    public function isPublish(){
        return $this->status===Status::Publish;
    }

    public function users(){
        return $this->belongsTo(User::class,'user_id');
    }

    public function posts(){
        return $this->belongsTo(Post::class,'post_id');
    }
}

resources/views/admin/comments/index.blade.php
@extends('admin.homepage')
@section('content')
<h3>{{__('news.plural.comment')}}</h3>
<hr>
<form action="{{route('admin.comment.index')}}" method="get">
  <div class="input-group">
  <input type="text" class="form-control" placeholder="Search" name="search">
    <select class="custom-select" name="status">
      <option value="none">...</option>
      @foreach ($status as $status)
      <option value="{{$status}}">{{$status}}</option>
      @endforeach
    </select>
    <div class="input-group-append">
      <button type="submit" class="btn btn-outline-secondary">{{__('news.plural.advance-search')}}</button>
    </div>
  </div>
</form>
<div>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">{{__('news.plural.user')}}</th>
            <th scope="col">{{__('news.plural.post')}}</th>
            <th scope="col">{{__('news.plural.content')}}</th>
            @can('only-admin',Auth::id())
            <th scope="col">{{__('news.plural.status')}}</th>
            <th scope="col">{{__('news.plural.deleted')}}</th>
            <th scope="col">{{__('news.plural.created')}}</th>
            <th scope="col">{{__('news.plural.updated')}}</th>
            <th scope="col">{{__('news.plural.action')}}</th>
            @endcan
            </tr>
        </thead>
        <tbody>
            @foreach ( $comments as $key=>$comment )
            <tr>
                <th scope="row">{{$key+1}}</th>
                <td>{{$comment->users->name}}</td>
                <td>{{$comment->posts->title}}</td>
                <td>{{$comment->content}}</td>
                <td>{{$comment->status}}</td>
                <td>{{$comment->deleted_at}}</td>
                <td>{{$comment->created_at}}</td>
                <td>{{$comment->updated_at}}</td>
                @can('only-admin',Auth::id())
                <td class="d-flex">
                    @if ($comment->status == 'Pending')
                    <a href="{{route('admin.comment.edit',$comment->id)}}">
                        <button type="button" class="btn btn-primary">{{__('news.user.publish')}}</button>
                    </a>
                    @endif
                    @if (!$comment->deleted_at)
                    <form method="post" action="{{route('admin.comment.destroy',$comment->id)}}">
                        @csrf
                        @method('delete')
                        <button type="submit" class="deleteBtn btn btn-danger">{{__('news.user.delete')}}</button>
                    </form>
                    @endif
                </td>
                @endcan
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection
@section('script')
<script>
$('.deleteBtn').click(function(e){
    e.preventDefault()
    if (confirm('{{__('news.plural.confirm')}}')) {
        $(e.target).closest('form').submit()
    }
})
</script>
@endsection