routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix'=>'admin/','namespace'=>'Admin', 'as'=>'admin.'],function(){
    Route::group(['middleware'=>'admin'],function(){
        //  Admin & Writter main page
        Route::get('','AdminHomeController@index')->name('homepage');
        Route::post('mark-as-read','AdminHomeController@markOneAsRead')->name('adminMarkAsRead');
        Route::get('mark-all-as-read','AdminHomeController@markAllAsRead')->name('adminMarkAllAsRead');

        //  Categories | Only Admin
        Route::resource('categories','CategoriesController');

        //  User | Full control for Admin | Only profile for Writter
        Route::resource('users','UserController');

        //  Post | Full control for Admin | Only post from Writter
        Route::resource('post','PostController');

        //  Notification | Full control for Admin | Only view from Writter
        Route::resource('notification','NotificationController');

        //  Image | Full control for Admin | Only image from Writter
        Route::resource('image','ImageController');

        // Comment| Only Admin
        Route::resource('comment','AdminCommentController')->only('index','edit','destroy');
    });
});

// All authenticated user
Route::group(['middleware'=>'auth'],function(){
    // Comment
    Route::controller('User\UserCommentController')->group(function(){
        Route::post('/comment/{post}','store')->name('pComment');
        Route::delete('/comment/{comment}','destroy')->name('deleteComment');
    });
    // Notification
    Route::controller('UserNotificationController')->group(function(){
        Route::post('/mark-as-read','markOneAsRead')->name('markAsRead');
        Route::get('/mark-all-read','markAllAsRead')->name('markAllRead');
    });
    // Like and unlike post
    Route::controller('User\LikeController')->group(function(){
        Route::post('/like/{post}','like')->name('like');
        Route::post('/unlike/{post}','unlike')->name('unlike');
    });
    // Profile
    Route::controller('User\UserProfileController')->group(function(){
        Route::get('/profile','profile')->name('user.profile');
        Route::put('/profile/{user}','update')->name('user.update');

    });
});

// Lang
Route::get('lang/{lang}','LanguageController')->name("lang");

// Authentication
    // Socialite
Route::controller('AuthProviderController')->group(function(){
    Route::get('/auth/{provider}/redirect', 'redirect')->name('socialLogin');
    Route::get('/auth/{provider}/callback', 'callback');
});
    // Setup password
Route::controller('User\UserSetupPasswordController')->group(function(){
    Route::get('/setup-password','index')->name('setupPassword');
    Route::post('/setup-password/sent','update')->name('pSetupPassword');
});
    //Manual
Route::controller('AuthController')->group(function(){
    Route::get('login','Login')->name('login');
    Route::post('login','pLogin')->name('pLogin');
    Route::get('register','register')->name('register');
    Route::post('register','pRegister')->name('pRegister');
    Route::get('logout','Logout')->name('logout');
});

// Page navigation
Route::get('/','User\UserHomeController')->name('homepage');
Route::get('post/{post}','User\ShowPostController@show')->name('showPost');
Route::get('filter','User\UserFilterController@filter')->name('postFilter');
Route::get('category/{category}','User\PostCategoryController')->name('postCategory');
Route::get('tag/{tag}','User\PostTagController')->name('postTag');


// Only for testing purpose
Route::get('/test',function(){
    return view('test');
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Image extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable = [
        'path',
        'user_id',
        'original_name'
    ];

    public function users()
    {
        return $this->belongsTo(User::class);
    }

    public function posts(){
        return $this->belongToMany(Post::class,'post_image','image_id','post_id');
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\RoleHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateImageRequest;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Imagick\Driver;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $images = RoleHelper::permissionForData(Auth::user(),Image::class);
        return view('admin.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.images.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateImageRequest $request)
    {
        $dataImages = $request->validated();
        $this->storeImage($dataImages);
        return redirect()->route('admin.image.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Image $image)
    {
        return view('admin.images.show',compact('image'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Image $image)
    {
        $image->delete();
        return redirect()->back();
    }

    private function storeImage($images)
    {
        foreach ($images['images'] as $image) {
            // Get and create unique name for image
            $originalName = $image->getClientOriginalName();
            $name = $image->hashname();
            $imageName = time().'-'.$name;
            // Store the image
            $path = $image->storeAs(
                'public', $imageName
            );
            // Get image path of the symlink folder
            $path = str_replace('public','storage',$path);
            // Resize the image using Intervention/Image
            $imgManager = new ImageManager(new Driver);
            $resizedImage = $imgManager->read($path);
            $resizedImage->resizeDown(960,540)->save();
            // Store the information of image to database
            $path = asset($path);
            $dataImage = array('user_id'=>Auth::id(),'path'=>$path,'original_name'=>$originalName);
            Image::create($dataImage);
        }
    }
}

resources/views/admin/images/create.blade.php
@extends('admin.homepage')
@section('styles')
<style>
    input[type="file"] {
    display: block;
    }
    .imageThumb {
    max-height: 75px;
    border: 2px solid;
    padding: 1px;
    cursor: pointer;
    }
    .pip {
    display: inline-block;
    margin: 10px 10px 0 0;
    }
    .remove {
    display: block;
    background: #444;
    border: 1px solid black;
    color: white;
    text-align: center;
    cursor: pointer;
    }
    .remove:hover {
    background: white;
    color: black;
    }
    #label{
        border: 1px solid black;

    }
    #label div{
        cursor: pointer;
        padding: 5px;
    }
</style>
@endsection
@section('content')
<h3>{{__('news.plural.image')}}</h3>
<hr>
<div class="field" align="left">
    <form action="{{route('admin.image.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <h3>{{__('news.plural.upload')}}</h3>
        <div>
            <input type="file" id="files" name="images[]" multiple hidden />
            <label id="label" for="files" class="rounded">
                <div>{{__('news.plural.upload-btn')}}</div>
            </label>
        </div>
        <button type="submit" class="btn btn-primary">{{__('news.user.send')}}</button>
    </form>
</div>
@endsection
@section('script')
<script>
  var selectedfiles;
    var selectedfile;
    var fileIndex;
    $(document).ready(function () {

        if (window.File && window.FileList && window.FileReader) {
            $("#files").on("change", function (e) {
                var files = e.target.files,
                    selectedfiles = files;
                console.log(selectedfiles);
                filesLength = files.length;

                for (var i = 0; i < filesLength; i++) {
                    selectedfile = files[i]
                    fileIndex = i;
                    // console.log(i, f);

                    var fileReader = new FileReader();
                    fileReader.onload = (function (e) {
                        var file = e.target;
                        $("<span class=\"pip\">" +
                            "<img class=\"imageThumb\" src=\"" + e.target.result +
                            "\" title=\"" + selectedfile.name + "\"/>" +
                            "<br/><span class=\"remove\" onclick=\"removeImage('" +
                            selectedfile.name + "')\">Remove image</span>" +
                            "</span>").insertAfter("#files");

                        $(".remove").click(function () {
                            $(this).parent(".pip").remove();
                        });



                    });
                    fileReader.readAsDataURL(selectedfile);
                }
            });
        } else {
            alert("Your browser doesn't support to File API")
        }
    });

    function removeImage(name) {
        selectedfiles = document.getElementById("files").files;
        var final = [];
        $.each(selectedfiles, function (index, value) {
            if (value.name !== name) {
                console.log(value);
                final.push(value);
            }
        });
        console.log('List', final);
        document.getElementById("files").files = new FileListItem(final);
    }

    function FileListItem(a) {
        a = [].slice.call(Array.isArray(a) ? a : arguments)
        for (var c, b = c = a.length, d = !0; b-- && d;) d = a[b] instanceof File
        if (!d) throw new TypeError("expected argument to FileList is File or array of File objects")
        for (b = (new ClipboardEvent("")).clipboardData || new DataTransfer; c--;) b.items.add(a[c])
        return b.files
    }
</script>
@endsection

resources/views/admin/images/index.blade.php
@extends('admin.homepage')
@section('styles')
<style>
    .img{
        max-width: 100%;
    }
    .img-container{
        width: 300px;
    }
    .delete{
        background: none;
        border: none;
    }
</style>
@endsection
@section('content')
<h3>{{__('news.plural.image')}}</h3>
<hr>
<a href="{{route('admin.image.create')}}">
    <button type="buton" class="btn btn-primary">{{__('news.user.create')}}</button>
</a>
<div class="d-flex flex-wrap">
    @foreach ($images as $image)
    <div class="d-flex flex-column align-items-center">
        <div class="img-container mx-2 my-2">
            <a href="{{route('admin.image.show',$image->id)}}">
                <img src="{{$image->path}}" alt="" class="img">
                <div style="">{{$image->original_name}}</div>
            </a>
        </div>
        <div>
            <form action="{{route('admin.image.destroy',$image->id)}}" method="post">
                @csrf
                @method('delete')
                <button class="delete" type="submit"><i class="fa-solid fa-x"></i></button>
            </form>
        </div>
    </div>
    @endforeach
</div>
@endsection
@section('script')
<script>
$('.delete').click(function(e){
    e.preventDefault()
    if (confirm('Are you sure?')==true) {
        $(e.target).closest('form').submit()
    }
})
</script>
@endsection

resources/views/admin/images/show.blade.php
@extends('admin.homepage')
@section('content')
<div>
    <button onclick="history.back()" class="btn btn-warning">{{__('news.redirect.back')}}</button>
</div>
<div class="d-flex flex-column align-items-center">
    <img src="{{$image->path}}" alt="">
    <p><i>{{$image->original_name}}</i></p>
</div>
@endsection