routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix'=>'admin/','namespace'=>'Admin', 'as'=>'admin.'],function(){
    Route::group(['middleware'=>'admin'],function(){
        //  Admin & Writter main page
        Route::get('','AdminHomeController@index')->name('homepage');
        Route::post('mark-as-read','AdminHomeController@markOneAsRead')->name('adminMarkAsRead');
        Route::get('mark-all-as-read','AdminHomeController@markAllAsRead')->name('adminMarkAllAsRead');

        //  Categories | Only Admin
        Route::resource('categories','CategoriesController');

        //  User | Full control for Admin | Only profile for Writter
        Route::resource('users','UserController');

        //  Post | Full control for Admin | Only post from Writter
        Route::resource('post','PostController');

        //  Notification | Full control for Admin | Only view from Writter
        Route::resource('notification','NotificationController');

        //  Image | Full control for Admin | Only image from Writter
        Route::resource('image','ImageController');

        // Comment| Only Admin
        Route::resource('comment','AdminCommentController')->only('index','edit','destroy');
    });
});

// All authenticated user
Route::group(['middleware'=>'auth'],function(){
    // Comment
    Route::controller('User\UserCommentController')->group(function(){
        Route::post('/comment/{post}','store')->name('pComment');
        Route::delete('/comment/{comment}','destroy')->name('deleteComment');
    });
    // Notification
    Route::controller('UserNotificationController')->group(function(){
        Route::post('/mark-as-read','markOneAsRead')->name('markAsRead');
        Route::get('/mark-all-read','markAllAsRead')->name('markAllRead');
    });
    // Like and unlike post
    Route::controller('User\LikeController')->group(function(){
        Route::post('/like/{post}','like')->name('like');
        Route::post('/unlike/{post}','unlike')->name('unlike');
    });
    // Profile
    Route::controller('User\UserProfileController')->group(function(){
        Route::get('/profile','profile')->name('user.profile');
        Route::put('/profile/{user}','update')->name('user.update');

    });
});

// Lang
Route::get('lang/{lang}','LanguageController')->name("lang");

// Authentication
    // Socialite
Route::controller('AuthProviderController')->group(function(){
    Route::get('/auth/{provider}/redirect', 'redirect')->name('socialLogin');
    Route::get('/auth/{provider}/callback', 'callback');
});
    // Setup password
Route::controller('User\UserSetupPasswordController')->group(function(){
    Route::get('/setup-password','index')->name('setupPassword');
    Route::post('/setup-password/sent','update')->name('pSetupPassword');
});
    //Manual
Route::controller('AuthController')->group(function(){
    Route::get('login','Login')->name('login');
    Route::post('login','pLogin')->name('pLogin');
    Route::get('register','register')->name('register');
    Route::post('register','pRegister')->name('pRegister');
    Route::get('logout','Logout')->name('logout');
});

// Page navigation
Route::get('/','User\UserHomeController')->name('homepage');
Route::get('post/{post}','User\ShowPostController@show')->name('showPost');
Route::get('filter','User\UserFilterController@filter')->name('postFilter');
Route::get('category/{category}','User\PostCategoryController')->name('postCategory');
Route::get('tag/{tag}','User\PostTagController')->name('postTag');


// Only for testing purpose
Route::get('/test',function(){
    return view('test');
});

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Categories\CategoriesRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Models\Categories;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Categories::class, 'category');
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Categories::withTrashed()->get();
        return view('admin.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CategoriesRequest $request)
    {
        $category=$request->validated();

        Categories::create($category);

        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Categories $category)
    {
        return view('admin.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Categories $category)
    {
        $updateCategory = $request->validated();

        $category->update($updateCategory);

        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Categories $category)
    {
        $category->delete();

        return redirect()->back();
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.homepage')
@section('content')
<h3>{{__('news.plural.category')}}</h3>
<hr>
<div>
    <form action="{{route('admin.categories.store')}}" method="post">
        @csrf
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">{{__('news.plural.title')}}</span>
            </div>
            <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="category" value="{{old('category')}}">
        </div>
        @foreach ($errors->get('category') as $categoryMessage)
                <div>{{$categoryMessage}}</div>
        @endforeach
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">{{__('news.plural.description')}}</span>
            </div>
            <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="description" value="{{old('description')}}">
        </div>
        @foreach ($errors->get('description') as $descriptionMessage)
                <div>{{$descriptionMessage}}</div>
        @endforeach
        <button type="submit" class="btn btn-primary">{{__('news.user.create')}}</button>
    </form>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.homepage')
@section('content')
<h3>{{__('news.plural.category')}}</h3>
<hr>
<div>
    <form action="{{route('admin.categories.update',$category->id)}}" method="post">
        @csrf
        @method('put')
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">{{__('news.plural.title')}}</span>
            </div>
            <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="category" value="{{old('category')?old('category'):$category->category}}">
        </div>
        @foreach ($errors->get('category') as $categoryMessage)
                <div>{{$categoryMessage}}</div>
        @endforeach
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">{{__('news.plural.description')}}</span>
            </div>
            <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="description" value="{{old('description')?old('description'):$category->description}}">
        </div>
        @foreach ($errors->get('description') as $descriptionMessage)
                <div>{{$descriptionMessage}}</div>
        @endforeach
        <input type="text" name="id" value="{{$category->id}}" hidden>
        <a href="{{route('admin.categories.index')}}">
            <button type="button" class="btn btn-danger">{{__('news.user.cancel')}}</button>
        </a>
        <button type="submit" class="btn btn-warning">{{__('news.user.update')}}</button>
    </form>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.homepage')
@section('content')
<h3>{{__('news.plural.category')}}</h3>
<hr>
<div>
    <a href="{{route('admin.categories.create')}}">
        <button type="button" class="btn btn-primary">{{__('news.user.create')}}</button>
    </a>
</div>
<div>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">{{__('news.plural.title')}}</th>
            <th scope="col">{{__('news.plural.description')}}</th>
            <th scope="col">{{__('news.plural.created')}}</th>
            <th scope="col">{{__('news.plural.updated')}}</th>
            <th scope="col">{{__('news.plural.deleted')}}</th>
            <th scope="col">{{__('news.plural.action')}}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ( $categories as $key=>$category )
            <tr>
                <th scope="row">{{$key+1}}</th>
                <td>{{$category->category}}</td>
                <td>{{$category->description}}</td>
                <td>{{$category->created_at}}</td>
                <td>{{$category->updated_at}}</td>
                <td>{{$category->deleted_at?$category->deleted_at:''}}</td>
                <td class="d-flex">
                    <a href="{{route('admin.categories.edit',$category->id)}}">
                        <button type="button" class="btn btn-warning">{{__('news.user.edit')}}</button>
                    </a>
                    <form action="{{route('admin.categories.destroy',$category->id)}}" method="POST">
                        @csrf
                        @method('delete')
                        <button onclick="" type="submit" class="deleteBtn btn btn-danger">{{__('news.user.delete')}}</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection
@section('script')
<script>
$('.deleteBtn').click(function(e){
    e.preventDefault()
    if (confirm('Are you sure?')==true) {
        $(e.target).closest('form').submit()
    }
})
</script>

@endsection